services:
  # Konfiguration für den Publisher-Service.
  stock-publisher:
    image: kiko46/stock-publisher
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app-network      

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123
  # Konfiguration für die MongoDB mit Replikation.
  mongo1:
    image: mongo:7.0
    ports:
      - "27017:27017" 
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s
    networks:
      - app-network      

  mongo2:
    image: mongo:7.0
    ports:
      - "27018:27018"  
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    volumes:
     - "mongo2_data:/data/db"
     - "mongo2_config:/data/configdb"
    networks:
      - app-network     

  mongo3:
    image: mongo:7.0
    ports:
      - "27019:27019"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
     - "mongo3_data:/data/db"
     - "mongo3_config:/data/configdb"
    networks:
      - app-network     

  stock-liveview1:
    image: kiko46/stock-liveview
    depends_on:
      - mongo1
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
      - MONGODB_DB=stockmarket
      - MONGODB_COLLECTION=stocks
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

  stock-liveview2:
    image: kiko46/stock-liveview
    depends_on:
      - mongo1
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
      - MONGODB_DB=stockmarket
      - MONGODB_COLLECTION=stocks
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
  
  consumer:
    image: kiko46/consumer
    depends_on:
      - rabbitmq
      - mongo1
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672
      - QUEUE_NAME=some-queue
      - MONGO_URL=mongodb://root:example@mongo1:27017,mongo2:27018,mongo3:27019/stockmarket?authSource=admin&replicaSet=rs0

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    depends_on:
      - stock-liveview1
      - stock-liveview2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
networks:
  app-network:

volumes:
  mongo1_data:
  mongo1_config:  
  mongo2_data:
  mongo2_config:
  mongo3_data:
  mongo3_config: